In [1]:
import json
import os
import grid2op
import numpy as np
from collections import defaultdict
from grid2op.PlotGrid import PlotMatplot
from lightsim2grid import LightSimBackend
from grid2op.Agent import DoNothingAgent
from grid2op.Runner import Runner
import matplotlib as mpl
import matplotlib.pyplot as plt
from tqdm.auto import tqdm  # for easy progress bar
import pandas as pd
from grid2op.Episode import EpisodeData
from ray.rllib.algorithms import ppo
from rl4pnc.evaluation.evaluation_agents import RllibAgent
from rl4pnc.grid2op_env.custom_environment import CustomizedGrid2OpEnvironment
from rl4pnc.grid2op_env.custom_env2 import RlGrid2OpEnv
from rl4pnc.experiments.yaml import load_config
from rl4pnc.evaluation.utils import instantiate_reward_class
from rl4pnc.grid2op_env.utils import load_actions

In [2]:
main_folder = "/Users/ericavandersar/surfdrive/Documents/Research/Result/Case14_Sandbox_ActSpaces/"
agent_name = "CustomPPO_RlGrid2OpEnv_6fdf8_00000_0_2024-05-06_05-12-14"
data_folder = os.path.join(main_folder, agent_name, "evaluation_episodes")
df = pd.read_csv(os.path.join(data_folder, "line_action_topo_data.csv"))
df

Unnamed: 0  chron_id  ts_danger  line_danger       rho  action_sub  \
0              0        20        513           17  0.955241           4   
1              1        20        514           17  0.950289           8   
2              2        20       2533           17  0.953320           3   
3              3        20       6741            9  0.951646           3   
4              4        20       6742            9  0.959878           3   
5              5        20       6743            9  0.956162           3   
6              6        20       6744            9  0.965621           3   
7              7        20       6745            9  0.973284           3   
8              8        20       6746            9  0.963417           3   
9              9        20       6747            9  0.966929           3   
10            10        20       6748            9  0.967001           3   
11            11        20       6749            9  0.966118           3   
12            12        20       6750            9  0.954786           3   
13            13        23        519           17  0.951275           4   
14            14        23        785           17  0.953516           8   
15            15        23        795           17  0.951343           3   
16            16        23        807           16  0.954650           3   
17            17        23        809           16  0.964688           3   
18            18        23        811           16  0.951908           3   
19            19        23        812           16  0.972310           3   
20            20        23        813           16  0.960202           3   
21            21        23        814           16  0.951978           3   
22            22        23        815           16  0.950828           3   
23            23        23        818           16  0.953781           3   
24            24        26        806            9  0.963970           4   
25            25        26        807            9  0.965289           8   
26            26        30        521            9  0.952655           8   
27            27        30       1086            4  0.954122           4   
28            28        30       1086           17  0.951372           4   
29            29        30       1088           17  0.966726           3   
30            30        30       3287            9  0.954086           3   
31            31        30       3288            9  0.952853           3   
32            32        30       3293            9  0.950179           3   
33            33        30       3294            9  0.957534           3   
34            34        30       3295            9  0.973233           3   
35            35        30       3296            9  0.995838           3   
36            36        30       3297            9  0.981252           3   
37            37        47        511           17  0.954385           4   
38            38        47        512           17  0.950570           8   
39            39        47       3102           17  0.951226           3   
40            40        65        790           17  0.955735           4   
41            41        65        793           17  0.954791           8   
42            42        65        802           17  0.961797           3   
43            43        65       2827           16  0.961290           3   
44            44        65       2829           16  0.957375           3   
45            45        65       3302            9  0.951766           3   
46            46        65       3303            9  0.960241           3   
47            47        65       4555           16  0.951588           3   
48            48        66       1087           17  0.958835           8   
49            49        66       1093            4  0.955342           4   
50            50        66       1093           17  0.956467           4   
51            51        66       1094           17  0.

In [120]:
df.value_counts("line_danger").reset_index(name='frequency')

line_danger  frequency
0            9        685
1           16        436
2           17        244
3            4         26
4            7          8

In [124]:
dfg = df.groupby(by=["action_sub", "action_topo"], as_index=False).size()
dfg

action_sub         action_topo  size
0           3  [2, 2, 1, 1, 2, 2]  1141
1           3  [2, 2, 1, 2, 1, 2]    53
2           4     [2, 1, 2, 2, 1]   103
3           8     [1, 1, 1, 2, 2]   102

In [49]:
df_sub_act = df.value_counts(["action_sub", "action_topo"]).reset_index(name='frequency')
df_sub_act

action_sub         action_topo  frequency
0           8     [1, 1, 1, 2, 2]       1512
1           1  [2, 2, 1, 2, 1, 2]        191
2           4     [2, 1, 1, 2, 2]        123

In [121]:
def collect_episode_data(env, store_trajectories_folder, li_episode):
    print(" Start collecting episode data ... ")
    chron = []
    surv = []
    
    for ep in tqdm(li_episode, total=len(li_episode)):
        full_path, episode_studied = ep
        this_episode = EpisodeData.from_disk(store_trajectories_folder, episode_studied)
        surv.append(this_episode.meta['nb_timestep_played'])
        chron.append(os.path.basename(os.path.normpath(this_episode.meta['chronics_path'])))
    all_data = {'chron': chron, 'survived': surv} 
    df_surv = pd.DataFrame(all_data)
    print(df_surv.head())
    df_surv.to_csv(os.path.join(store_trajectories_folder, "survival.csv"), index=False)
    return df_surv

In [122]:
env = grid2op.make("l2rpn_case14_sandbox", backend=LightSimBackend())
li_episode = EpisodeData.list_episode(data_folder)
df_sur = collect_episode_data(env, data_folder, li_episode)
df_sur

 Start collecting episode data ... 


  0%|          | 0/100 [00:00<?, ?it/s]

  chron  survived
0  0020      8064
1  0023      8064
2  0026      8064
3  0030      8064
4  0047      8064


chron  survived
0   0020      8064
1   0023      8064
2   0026      8064
3   0030      8064
4   0047      8064
5   0065      8064
6   0066      8064
7   0075      8064
8   0076      8064
9   0103      8064
10  0110      8064
11  0128      8064
12  0129      8064
13  0141      8064
14  0144      6763
15  0153      8064
16  0154      8064
17  0156      8064
18  0157      8064
19  0162      8064
20  0164      8064
21  0172      8064
22  0179      8064
23  0192      8064
24  0196      8064
25  0206      8064
26  0222      8064
27  0228      8064
28  0230      8064
29  0267      8064
30  0274      8064
31  0286      8064
32  0287      8064
33  0292      8064
34  0303      8064
35  0319      8064
36  0332      8064
37  0341      8064
38  0348      8064
39  0355      8064
40  0360      8064
41  0369      8064
42  0381      8064
43  0387       998
44  0391      8064
45  0401      8064
46  0417      8064
47  0418      8064
48  0454      8064
49  0474      8064
50  0481      8064
51  0486      8064
52  0504      8064
53  0505      8064
54  0511      8064
55  0513      8064
56  0516      8064
57  0529      8064
58  0531      8064
59  0533      8064
60  0539      8064
61  0545      8064
62  0547      8064
63  0565      8064
64  0580      8064
65  0595      8064
66  0610      8064
67  0612      8064
68  0614      8064
69  0628      8064
70  0636      8064
71  0703      3303
72  0721      8064
73  0757      8064
74  0763      8064
75  0766      8064
76  0770      8064
77  0774      8064
78  0779      8064
79  0812      3572
80  0842      3588
81  0844      5303
82  0845      8064
83  0852      8064
84  0868      8064
85  0869      8064
86  0870      8064
87  0871      8064
88  0879      3005
89  0891      8064
90  0895      3286
91  0924      8064
92  0925      8064
93  0950      8064
94  0954      8064
95  0962      8064
96  0986      8064
97  0993      8064
98  0995      8064
99  1000      8064

In [6]:
env = grid2op.make("l2rpn_case14_sandbox", backend=LightSimBackend())
li_episode = EpisodeData.list_episode(data_folder)
full_path, episode_studied = li_episode[0]
this_episode = EpisodeData.from_disk(data_folder, episode_studied)
this_episode.META

'episode_meta.json'

In [7]:
this_episode.meta

{'agent_seed': None,
 'backend_type': 'LightSimBackend_l2rpn_case14_sandbox',
 'chronics_max_timestep': '8064',
 'chronics_path': '/Users/ericavandersar/data_grid2op/l2rpn_case14_sandbox/chronics/0020',
 'cumulative_reward': 507867.53125,
 'env_seed': None,
 'env_type': 'Environment_l2rpn_case14_sandbox',
 'grid_path': '/Users/ericavandersar/data_grid2op/l2rpn_case14_sandbox/grid.json',
 'nb_timestep_played': 8064}

In [130]:
def actions_per_agent(agents, main_folder, reset_topo=False):
    data_dict = {}
    for agent_name in agents:
        # Get agent code
        agent_code = agent_name.split("_")[2]

        # Get action space
        agent_path = os.path.join(main_folder, agent_name)
        with open(os.path.join(agent_path,'params.json')) as json_file:
            agent_pars = json.load(json_file)
        data_dict[agent_code] = {"action_space": agent_pars["env_config"]["action_space"]}
        
        # Timesteps survived
        if reset_topo:
            data_folder = os.path.join(agent_path, "evaluation_episodes_testreset")
        else:
            data_folder = os.path.join(agent_path, "evaluation_episodes")
        df_surv = pd.read_csv(os.path.join(data_folder, "survival.csv"))
        data_dict[agent_code]["mean_surv_ts"] = df_surv.survived.mean()

        
        # Size action space
        lib_dir = "/Users/ericavandersar/Documents/Python_Projects/Research/rl4pnc"
        path = os.path.join(
                lib_dir,
                f"data/action_spaces/{env.name}/{act_space}.json",
            )
        actions = load_actions(path, env)
        data_dict[agent_code]["n_actions"] = len(actions)
        
        # action frequency
        df = pd.read_csv(os.path.join(data_folder, "line_action_topo_data.csv"))
        df_sub_act = df.value_counts(["action_sub", "action_topo"]).reset_index(name='frequency')
        print(df_sub_act)
        for idx, row in df_sub_act.iterrows():
            data_dict[agent_code][f'sub{row["action_sub"]}_{row["action_topo"]}'] = row["frequency"]
        df_line_danger = df.value_counts("line_danger").reset_index(name='frequency')
        for idx, row in df_line_danger.iterrows():
            data_dict[agent_code][f'line_{row["line_danger"]}'] = row["frequency"]
    new_df = pd.DataFrame.from_dict(data_dict, orient='index')
    new_df = new_df[
    ['action_space', 'mean_surv_ts', 'n_actions'] 
    + sorted([col for col in new_df if col.startswith('sub')]) 
    + [col for col in new_df if col.startswith('line')]
    ]
    new_df.to_csv(os.path.join(main_folder, "agents_overview.csv"), index=False)
    # order columns:
    return new_df

In [39]:
lib_dir = "/Users/ericavandersar/Documents/Python_Projects/Research/rl4pnc"
path = os.path.join(
        lib_dir,
        f"data/action_spaces/{env.name}/{act_space}.json",
    )
possible_substation_actions = load_actions(path, env)
print('number actions: ', len(possible_substation_actions))

number actions:  140


In [50]:
df_sub_act

action_sub         action_topo  frequency
0           8     [1, 1, 1, 2, 2]       1512
1           1  [2, 2, 1, 2, 1, 2]        191
2           4     [2, 1, 1, 2, 2]        123

In [54]:
for idx, row in df_sub_act.iterrows():
    sub_act = f'sub{row["action_sub"]}_{row["action_topo"]}'
    freq = row["frequency"]
    print(f"substation actions {sub_act} frequency {freq}")

substation actions sub8_[1, 1, 1, 2, 2] frequency 1512
substation actions sub1_[2, 2, 1, 2, 1, 2] frequency 191
substation actions sub4_[2, 1, 1, 2, 2] frequency 123


In [55]:
df_sur.survived.mean()

8064.0

In [131]:
agents = [
    "CustomPPO_RlGrid2OpEnv_736a5_00000_0_2024-05-06_03-10-39",
    "CustomPPO_RlGrid2OpEnv_7d675_00000_0_2024-05-06_10-20-25",
    "CustomPPO_RlGrid2OpEnv_6fdf8_00000_0_2024-05-06_05-12-14",
    ]
df_res = actions_per_agent(agents, main_folder)
df_res

   action_sub         action_topo  frequency
0           8     [1, 1, 1, 2, 2]       1512
1           1  [2, 2, 1, 2, 1, 2]        191
2           4     [2, 1, 1, 2, 2]        123
   action_sub         action_topo  frequency
0           8     [1, 1, 1, 2, 2]        510
1           4     [2, 1, 1, 2, 2]        297
2           3  [2, 2, 1, 2, 1, 2]        143
3           1  [2, 2, 1, 1, 1, 2]         32
4          11           [1, 1, 1]          1
   action_sub         action_topo  frequency
0           3  [2, 2, 1, 1, 2, 2]       1141
1           4     [2, 1, 2, 2, 1]        103
2           8     [1, 1, 1, 2, 2]        102
3           3  [2, 2, 1, 2, 1, 2]         53


action_space  mean_survived_ts  n_actions  sub11_[1, 1, 1]  \
736a5       medha_DN_rev           8064.00        140              NaN   
7d675       medha_DN_rev           7854.53        140              1.0   
6fdf8  medha_dn_optshunt           7717.06        140              NaN   

       sub1_[2, 2, 1, 1, 1, 2]  sub1_[2, 2, 1, 2, 1, 2]  \
736a5                      NaN                    191.0   
7d675                     32.0                      NaN   
6fdf8                      NaN                      NaN   

       sub3_[2, 2, 1, 1, 2, 2]  sub3_[2, 2, 1, 2, 1, 2]  sub4_[2, 1, 1, 2, 2]  \
736a5                      NaN                      NaN                 123.0   
7d675                      NaN                    143.0                 297.0   
6fdf8                   1141.0                     53.0                   NaN   

       sub4_[2, 1, 2, 2, 1]  sub8_[1, 1, 1, 2, 2]  line_9  line_17  line_16  \
736a5                   NaN                  1512    1372      225      153   
7d675                   NaN                   510     357      396      128   
6fdf8                 103.0                   102     685      244      436   

       line_7  line_4  
736a5      43      33  
7d675       3      99  
6fdf8       8      26

In [3]:
env = grid2op.make("l2rpn_case14_sandbox", backend=LightSimBackend())
lib_dir = "/Users/ericavandersar/Documents/Python_Projects/Research/rl4pnc"
act_space = "medha_dn_allshunt_maxrho1.0-30-100_gr"
path = os.path.join(
    lib_dir,
    f"data/action_spaces/{env.name}/{act_space}.json",
)
actions = load_actions(path, env)

In [21]:
action_dict = defaultdict(list)
for action in actions:
    act = action.set_bus
    if any(act!=0):
        print(f" Substation {env._topo_vect_to_sub[act != 0][0]} - topo config: {list(act[act != 0].astype(int))}" )
        action_dict[f"substation {env._topo_vect_to_sub[act != 0][0]}"].append(list(act[act != 0].astype(int)))
    else: 
        print(15) 

 Substation 0 - topo config: [1, 1, 1]
 Substation 1 - topo config: [2, 2, 1, 2, 1, 2]
 Substation 3 - topo config: [2, 1, 2, 2, 2, 1]
 Substation 3 - topo config: [2, 1, 1, 2, 2, 1]
 Substation 3 - topo config: [2, 1, 1, 1, 1, 2]
 Substation 4 - topo config: [2, 1, 2, 2, 1]
 Substation 4 - topo config: [2, 1, 2, 1, 2]
 Substation 4 - topo config: [2, 1, 1, 2, 2]
 Substation 5 - topo config: [1, 1, 1, 1, 1, 1, 1]
 Substation 5 - topo config: [2, 1, 2, 2, 1, 2, 2]
 Substation 5 - topo config: [2, 1, 1, 1, 1, 2, 1]
 Substation 8 - topo config: [1, 1, 1, 1, 1]
 Substation 9 - topo config: [1, 1, 1]
 Substation 8 - topo config: [1, 1, 1, 2, 2]
 Substation 8 - topo config: [2, 2, 2, 1, 1]
 Substation 1 - topo config: [1, 1, 1, 1, 1, 1]
 Substation 3 - topo config: [1, 1, 1, 1, 1, 1]
 Substation 4 - topo config: [1, 1, 1, 1, 1]


In [25]:
action_dict

defaultdict(list,
            {'substation 0': [[1, 1, 1]],
             'substation 1': [[2, 2, 1, 2, 1, 2], [1, 1, 1, 1, 1, 1]],
             'substation 3': [[2, 1, 2, 2, 2, 1],
              [2, 1, 1, 2, 2, 1],
              [2, 1, 1, 1, 1, 2],
              [1, 1, 1, 1, 1, 1]],
             'substation 4': [[2, 1, 2, 2, 1],
              [2, 1, 2, 1, 2],
              [2, 1, 1, 2, 2],
              [1, 1, 1, 1, 1]],
             'substation 5': [[1, 1, 1, 1, 1, 1, 1],
              [2, 1, 2, 2, 1, 2, 2],
              [2, 1, 1, 1, 1, 2, 1]],
             'substation 8': [[1, 1, 1, 1, 1],
              [1, 1, 1, 2, 2],
              [2, 2, 2, 1, 1]],
             'substation 9': [[1, 1, 1]]})

In [42]:
action = actions[1].set_bus
action

array([0, 0, 0, 2, 2, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [38]:
obs = env.reset()
obs.topo_vect

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [43]:
action[action!=0]

array([2, 2, 1, 2, 1, 2], dtype=int32)

In [44]:
obs.topo_vect[action!=0]

array([1, 1, 1, 1, 1, 1], dtype=int32)

In [46]:
env.current_obs.topo_vect

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [49]:
np.all(obs.topo_vect[action!=0] == action[action!=0])

False